version: '3.1'

services:
  metabase:
    image: 073865013699.dkr.ecr.us-east-1.amazonaws.com/dp-metabase:v0.60.2-1-amd64
    container_name: metabase
    restart: always
    ports:
      - "3000:3000"
    environment:
      MB_HTTP_TIMEOUT: "5000"
      JAVA_TIMEZONE: "UTC"
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: "metabase"
      MB_DB_PORT: "5432"
      MB_DB_USER: "metabase_user"
      MB_DB_HOST: "dev-dp-postgres-master.cjjtajzwlxu5.us-east-1.rds.amazonaws.com"
      MB_PLUGINS_DIR: "plugins"
      MAX_SESSION_AGE: "1440"
      MB_DB_PASS: "${METABASE_DEV_DB_PASSWORD}"
      MB_LLM_ANTHROPIC_API_BASE_URL: "https://portkey.cnstrc.com"
    networks:
      - metabasenet

networks:
  metabasenet:
